/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gputpl;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Leandro
 */
public class Metoda_Chavez_Guillen extends javax.swing.JFrame {

    /**
     * Creates new form PolinomioEcologico
     */
    public Metoda_Chavez_Guillen() {

        initComponents();
        new PegarExcel(tabladatos);
        this.setLocationRelativeTo(null);

        //    textQ.setEnabled(false);
        filtroTeclas();
    }

    public void filtroTeclas() {
        Document document1 = pendiente.getDocument();
        DocumentFilter documentFilter1 = new FiltraEntrada(FiltraEntrada.NUM_LETRAS, 10, false);
        ((AbstractDocument) document1).setDocumentFilter(documentFilter1);

        Document document2 = lai.getDocument();
        DocumentFilter documentFilter2 = new FiltraEntrada(FiltraEntrada.NUM_LETRAS, 10, false);
        ((AbstractDocument) document2).setDocumentFilter(documentFilter2);

        Document document4 = areacuenca.getDocument();
        DocumentFilter documentFilter4 = new FiltraEntrada(FiltraEntrada.NUM_LETRAS, 10, false);
        ((AbstractDocument) document4).setDocumentFilter(documentFilter4);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pendiente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        areacuenca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lai = new javax.swing.JTextField();
        labepi2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        labepi3 = new javax.swing.JLabel();
        labepi4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        desviaciones = new javax.swing.JTextField();
        promediopre = new javax.swing.JTextField();
        infiltracion = new javax.swing.JTextField();
        textfc = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Pendiente (S) ");

        jLabel4.setText("Área total de la Cuenca");

        jLabel1.setText("Usted Selecciono el Metodo de Chavez-Vicente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Su formula es Q=e^(a-0.0645846*Ln(I)-9.53942*MAI*(I/S)+4.8904*MAI)*A");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lai.setToolTipText("Ingrese valores de 0 a 0.735");

        labepi2.setText("Infiltración (I)");

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ENERO", null, null, null, null, null},
                {"FEBRERO", null, null, null, null, null},
                {"MARZO", null, null, null, null, null},
                {"ABRIL", null, null, null, null, null},
                {"MAYO", null, null, null, null, null},
                {"JUNIO", null, null, null, null, null},
                {"JULIO", null, null, null, null, null},
                {"AGOSTO", null, null, null, null, null},
                {"SEPTIEMBRE", null, null, null, null, null},
                {"OCTUBRE", null, null, null, null, null},
                {"NOVIEMBRE", null, null, null, null, null},
                {"DICIEMBRE", null, null, null, null, null}
            },
            new String [] {
                "MES", "PM", "P75", "ETO", "MAI", "QM"
            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        labepi3.setText("Indice de Covertura Vegetal (fc)");

        labepi4.setText("LAI");

        jLabel6.setText("Desviacion Estandar (SD)");

        jLabel7.setText("Precipitación Promedio (X)");

        jToggleButton1.setText("Tabla (Español)");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Tabla (Ingles)");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jToggleButton1))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(labepi2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(labepi3)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labepi4)
                                            .addGap(144, 144, 144)
                                            .addComponent(jToggleButton2))))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(areacuenca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(promediopre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(desviaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infiltracion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(promediopre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desviaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areacuenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pendiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labepi2)
                    .addComponent(infiltracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labepi3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labepi4)
                            .addComponent(lai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1)
                            .addComponent(jToggleButton2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(textfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DecimalFormat df = new DecimalFormat("#####.##");
        double f = 0;
        double[] dato = new double[12];
        for (int i = 0; i < 12; i++) {
            try {
                f += (double) Double.parseDouble(tabladatos.getModel().getValueAt(i, 1) + "");
                dato[i] = (double) Double.parseDouble(tabladatos.getModel().getValueAt(i, 1) + "");
                System.out.println(dato[i]);
            } catch (Exception e) {
                f += 0;
                dato[i] = 0;
            }
        }
        double promedio = f / 12;
        double sumatoria = 0;
        for (int i = 0; i < dato.length; i++) {
            sumatoria += Math.pow((dato[i] - promedio), 2);
        }
        double val =  sumatoria / 11;
        double desviacion = Math.sqrt(val);
        promediopre.setText("" + df.format(promedio));
        desviaciones.setText("" + df.format(desviacion));
        double pt = 0;
        double fc=1-Math.exp(0.5* Double.parseDouble(lai.getText()));
        textfc.setText(df.format(fc)+"");
        double areac=Double.parseDouble(areacuenca.getText());
        double pen=Double.parseDouble(pendiente.getText());
        double in=Double.parseDouble(infiltracion.getText());
        double a=0;
        for (int i = 0; i < 12; i++) {
            
            if (dato[i] > 350) {
                System.out.println("ENTRO AQUI 1"+dato[i]);
                pt = dato[i] - (2.93 * desviacion);
            } else {
                if (200 < dato[i] && dato[i] < 350) {
                    System.out.println("ENTRO AQUI 2"+dato[i]);
                    pt = dato[i] - (2.74 * desviacion);
                } else {
                    if (100 < dato[i] && dato[i] <200) {
                        System.out.println("ENTRO AQUI 3"+dato[i]);
                        pt = dato[i] - (1.48 * desviacion);
                    }
                    else
                    {
                        System.out.println("ENTRO AQUI 4"+dato[i]);
                        pt = dato[i] - (0.74 * desviacion);
                    }
                }
            }
            tabladatos.getModel().setValueAt(df.format(pt), i, 2);
            double valormai=0;
            try{
            valormai=pt/Double.parseDouble(tabladatos.getModel().getValueAt(i, 3) + "");
                    }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, e, "Ingrese los valores correctos", i);
            }
            if(i<=5){
                
                a=4.7;
            }
            else{
                if(i==6||i==11||i==12)
                {
                    System.out.println("entro +"+i);
                    a=3.9;
                }
                if(i==7||i==10)
                {
                    a=2.4;
                }
                if(i==8||i==9)
                {
                    a=1.1;
                }
            }
            ///a-0.645846*Ln(I)-9.53942*MAI*(I/S)+4.8904*MAI)*A
            double qm=((Math.exp(a-(0.645846*Math.log(in))-(9.53942*valormai*(in/pen))+4.8904*valormai))/1000)*areac;
            tabladatos.getModel().setValueAt(df.format(valormai), i, 4);
            tabladatos.getModel().setValueAt(df.format(qm), i, 5);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Tabla1 tb1= new Tabla1();
        tb1.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Tabla2 tb= new Tabla2();
        tb.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metoda_Chavez_Guillen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metoda_Chavez_Guillen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metoda_Chavez_Guillen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metoda_Chavez_Guillen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metoda_Chavez_Guillen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areacuenca;
    private javax.swing.JTextField desviaciones;
    private javax.swing.JTextField infiltracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel labepi2;
    private javax.swing.JLabel labepi3;
    private javax.swing.JLabel labepi4;
    private javax.swing.JTextField lai;
    private javax.swing.JTextField pendiente;
    private javax.swing.JTextField promediopre;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField textfc;
    // End of variables declaration//GEN-END:variables
}
