/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gputpl;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class Metodo_Chavez extends javax.swing.JFrame {

    /**
     * Creates new form PolinomioEcologico
     */
    public Metodo_Chavez() {

        initComponents();
        this.setLocationRelativeTo(null);
        new PegarExcel(tabladatos);
        //textQ.setEnabled(false);
        filtroTeclas();
    }

    public void filtroTeclas() {
//        //Document document1 = textP1.getDocument();
//        DocumentFilter documentFilter1 = new FiltraEntrada(FiltraEntrada.NUM_LETRAS, 10, false);
//        ((AbstractDocument) document1).setDocumentFilter(documentFilter1);
//
//        Document document2 = textN.getDocument();
//        DocumentFilter documentFilter2 = new FiltraEntrada(FiltraEntrada.NUM_LETRAS, 10, false);
//        ((AbstractDocument) document2).setDocumentFilter(documentFilter2);
//
//        Document document4 = textA.getDocument();
//        DocumentFilter documentFilter4 = new FiltraEntrada(FiltraEntrada.NUM_LETRAS, 10, false);
//        ((AbstractDocument) document4).setDocumentFilter(documentFilter4);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        desviaciones = new javax.swing.JTextField();
        promediopre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        coeficientesi = new javax.swing.JLabel();
        labepi2 = new javax.swing.JLabel();
        pendiente = new javax.swing.JTextField();
        labepi3 = new javax.swing.JLabel();
        textfc = new javax.swing.JTextField();
        labepi4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        lai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        area = new javax.swing.JTextField();
        labepi5 = new javax.swing.JLabel();
        infiltracion = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usted Selecciono el Metodo de Chavez");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Su formula es Q75=a*e^(b*MAI)");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        desviaciones.setText("Desviación Estandar(SD )");
        desviaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desviacionesActionPerformed(evt);
            }
        });

        promediopre.setText("Promedio de las Precipitaciones (X)");
        promediopre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promediopreActionPerformed(evt);
            }
        });

        jLabel3.setText("Promedio Precipitaciones");

        jLabel4.setText("Desviacion Estandar");

        labepi2.setText("Infiltración (I) mm/h-1");

        labepi3.setText("Indice de Covertura Vegetal (fc)");

        textfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfcActionPerformed(evt);
            }
        });

        labepi4.setText("LAI");

        jToggleButton1.setText("Tabla (Español)");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Tabla (Ingles)");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        lai.setToolTipText("Ingrese valores de 0 a 0.735");

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ENERO", null, null, null, null, null},
                {"FEBRERO", null, null, null, null, null},
                {"MARZO", null, null, null, null, null},
                {"ABRIL", null, null, null, null, null},
                {"MAYO", null, null, null, null, null},
                {"JUNIO", null, null, null, null, null},
                {"JULIO", null, null, null, null, null},
                {"AGOSTO", null, null, null, null, null},
                {"SEPTIEMBRE", null, null, null, null, null},
                {"OCTUBRE", null, null, null, null, null},
                {"NOVIEMBRE", null, null, null, null, null},
                {"DICIEMBRE", null, null, null, null, null}
            },
            new String [] {
                "MES", "PM", "P75", "ETO", "MAI", "Q75"
            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        jLabel6.setText("Area");

        area.setToolTipText("");

        labepi5.setText("Pendiente (S) %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(coeficientesi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(area))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labepi4)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2)
                        .addGap(18, 18, 18)
                        .addComponent(lai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labepi3)
                            .addComponent(labepi2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infiltracion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGap(380, 380, 380))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(labepi5))
                    .addGap(56, 56, 56)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(promediopre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(desviaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promediopre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desviaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labepi5)
                    .addComponent(pendiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labepi2)
                    .addComponent(infiltracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labepi3)
                    .addComponent(textfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(coeficientesi)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labepi4)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(lai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desviacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desviacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desviacionesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DecimalFormat df = new DecimalFormat("#####.##");
        NumberFormat format = NumberFormat.getInstance(Locale.FRANCE);
        //  Number number = format.parse("1,234");
        double f = 0;
        double[] dato = new double[12];
        for (int i = 0; i < 12; i++) {
            try {
                f += (double) Double.parseDouble(tabladatos.getModel().getValueAt(i, 1) + "");
                dato[i] = (double) Double.parseDouble(tabladatos.getModel().getValueAt(i, 1) + "");
            } catch (Exception e) {
                f += 0;
                dato[i] = 0;
            }
        }
        double promedio = f / 12;
        double sumatoria = 0;
        for (int i = 0; i < dato.length; i++) {
            sumatoria += Math.pow((dato[i] - promedio), 2);
        }
        double val = sumatoria / 11;
        double desviacion = Math.sqrt(val);
        promediopre.setText("" + df.format(promedio));
        desviaciones.setText("" + df.format(desviacion));
        double a = 0;
        double b = 0;
        System.out.println(Double.parseDouble(lai.getText()));
        double fc = 1 - (Math.exp(1) * (0.5 * Double.parseDouble(lai.getText())));
        textfc.setText(df.format(fc) + "");
        a = Math.pow(10, -8) * Math.pow(fc / Double.parseDouble(infiltracion.getText()), -7.2474);
        b = -3.2951 * (Double.parseDouble(infiltracion.getText()) / Double.parseDouble(pendiente.getText())) + 5.33;
        double pt = 0;
        for (int i = 0; i < 12; i++) {
            
            if (dato[i] > 350) {
                System.out.println("ENTRO AQUI 1"+dato[i]);
                pt = dato[i] - (2.93 * desviacion);
            } else {
                if (200 < dato[i] && dato[i] < 350) {
                    System.out.println("ENTRO AQUI 2"+dato[i]);
                    pt = dato[i] - (2.74 * desviacion);
                } else {
                    if (100 < dato[i] && dato[i] <200) {
                        System.out.println("ENTRO AQUI 3"+dato[i]);
                        pt = dato[i] - (1.48 * desviacion);
                    }
                    else
                    {
                        System.out.println("ENTRO AQUI 4"+dato[i]);
                        pt = dato[i] - (0.74 * desviacion);
                    }
                }
            }

            tabladatos.getModel().setValueAt(df.format(pt), i, 2);
            double valormai = 0;
            try {
                valormai = pt / (double) Double.parseDouble(tabladatos.getModel().getValueAt(i, 3) + "");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e, "Ingrese los valores correctos", i);
            }
            ///Qm= a*e(b*MAi)*A
            double qm = 0;
            tabladatos.getModel().setValueAt(df.format(valormai), i, 4);
            qm = a * Math.exp(b * valormai);
            double resultado = (qm / 1000) * Double.parseDouble(area.getText());
            tabladatos.getModel().setValueAt(df.format(resultado), i, 5);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void promediopreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promediopreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promediopreActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Tabla2 tb = new Tabla2();
        tb.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Tabla1 tb1 = new Tabla1();
        tb1.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void textfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metodo_Chavez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metodo_Chavez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metodo_Chavez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metodo_Chavez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metodo_Chavez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JLabel coeficientesi;
    private javax.swing.JTextField desviaciones;
    private javax.swing.JTextField infiltracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel labepi2;
    private javax.swing.JLabel labepi3;
    private javax.swing.JLabel labepi4;
    private javax.swing.JLabel labepi5;
    private javax.swing.JTextField lai;
    private javax.swing.JTextField pendiente;
    private javax.swing.JTextField promediopre;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField textfc;
    // End of variables declaration//GEN-END:variables
}
